name: Build software version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: false
  push:
    tags:
      - 'v*' # Matching documentation

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Retrieve version
        id: get_version
        run: |
          $version = ${{ github.event.inputs.version }}
          if (-not $version) {
            $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          }
          echo "::set-output name=version::$version"
    
      - name: Install dependencies
        run: pip3 install -r packaging-requirements.txt

      - name: Build executable
        run: pyinstaller ui-qt6-win.spec

      - name: Create zip file
        run: |
          $version = ${{ steps.get_version.outputs.version }}
          $folder = "software-$version"
          New-Item -Path $folder -ItemType Directory
          Copy-Item -Path dist/wm2.exe -Destination $folder -Force
          Copy-Item -Path wm2.ini -Destination $folder -Force
          Compress-Archive -Path $folder -DestinationPath software-$version.zip
