name: Generate PDF Documentation

on:
  push:
    tags:
      - 'd*' # Matching documentation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: sudo apt-get install pandoc texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

      - name: Build PDF documentation
        run: pandoc --verbose -s -o /tmp/quickguide.pdf USAGE.md > /tmp/output.log 2>&1
        continue-on-error: true

      - name: List directory
        run: ls -l . /tmp .github/workflows

      - name: View output log
        run: cat /tmp/output.log
  
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: quickguide
          path: /tmp/quickguide.pdf
